#!/bin/bash
set -x
set -euo pipefail

export ETCD_PORT=${ETCD_PORT:-2379}
export HOST_IP=${HOST_IP:-10.1.92.1}
export ETCD=$HOST_IP:$ETCD_PORT

echo "[nginx] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
# it could say it couldn't reload nginx. That is because that nginx may be not started at the very first time
#    but confd already detect there is at least one key/value already existed in the etcd cluster
until confd -onetime --log-level debug -node=http://$ETCD -config-file /etc/confd/conf.d/nginx.toml; do
    echo "[nginx] waiting for confd to create initial nginx configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch for changes every 10 seconds
confd -interval 10 --log-level debug -node=http://$ETCD -config-file /etc/confd/conf.d/nginx.toml &

echo "[nginx] confd is now monitoring etcd for changes..."

# Start the Nginx service using the generated config
echo "[nginx] starting nginx service..."
/usr/sbin/nginx &

# Follow the logs to allow the script to continue running
while ! tail -f /var/log/nginx*.log ; do sleep 2 ; done
